### ISSUE TITLE
ReadClass - no parameterless constructor

### ISSUE THREAD

**Issue by eltigre4jc** [killnine/s7netplus#104]
I try to read a class that looks like below:
`Public Class ReadStatus

    Public Property VALID As Boolean
    Public Property BUSY As Boolean
    Public Property OutputERROR As Boolean
    Public Property Status As String
    Public Property LEN As UInt16

    Public Sub New()

    End Sub

End Class`

But it gives me the error: "No parameterless constructor defined for this object."
`   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at S7.Net.Types.Class.GetIncreasedNumberOfBytes(Double startingNumberOfBytes, Type type)
   at S7.Net.Types.Class.GetClassSize(Object instance)
   at S7.Net.Plc.ReadClass(Object sourceClass, Int32 db, Int32 startByteAdr)`

I tried also, without the constructor from my class, but also no success. in 1.0.7 I know it worked

**Comment by eltigre4jc** [comment]
I have to replace String with Byte() and now it works:

` Dim _status As Byte() = New Byte(4) {}

    Public Property Status As Byte()
        Get
            Return _status
        End Get
        Set(value As Byte())
            _status = value
        End Set
    End Property

    Public ReadOnly Property StatusValue As String = System.Text.Encoding.ASCII.GetString(_status)`
